##spring.application.name=JournalApp
##spring.data.mongodb.uri=
##spring.data.mongodb.port=27017
##spring.data.mongodb.database=journaldb
##spring.data.mongodb.auto-index-creation=true
#
#spring:
#  data:
#    mongodb:
#      uri: 
#      database: journaldb
#      auto-index-creation: true
#
#server:
#  port: 8081
#  servlet:
#    context-path: /journal
spring:
  data:
    redis:
      host: redis-15641.c212.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 15641
      password: password
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: nishishah0104@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      nishioffduty:
        journalApp: DEBUG

weather:
  api:
    key: b7a3896af8ad1b781078710ddf840891
